Traceback (most recent call last):
  File "/home/adminloria/anaconda3/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/adminloria/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/adminloria/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/adminloria/anaconda3/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
  File "/home/adminloria/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/adminloria/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/adminloria/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/adminloria/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
cursor = db.NYfood.find({"cuisine": "Bakery"})
cursor=list(cursor)
print(cursor[0]["address"]["loc"]["coordinates"])
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mIndexError[0m                                Traceback (most recent call last)
Cell [0;32mIn[12], line 3[0m
[1;32m      1[0m cursor [38;5;241m=[39m db[38;5;241m.[39mNYfood[38;5;241m.[39mfind({[38;5;124m"[39m[38;5;124mcuisine[39m[38;5;124m"[39m: [38;5;124m"[39m[38;5;124mBakery[39m[38;5;124m"[39m})
[1;32m      2[0m cursor[38;5;241m=[39m[38;5;28mlist[39m(cursor)
[0;32m----> 3[0m [38;5;28mprint[39m([43mcursor[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m[[38;5;124m"[39m[38;5;124maddress[39m[38;5;124m"[39m][[38;5;124m"[39m[38;5;124mloc[39m[38;5;124m"[39m][[38;5;124m"[39m[38;5;124mcoordinates[39m[38;5;124m"[39m])

[0;31mIndexError[0m: list index out of range

